name: CI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Downgrade to Node.js 18.x (LTS and compatible with Gatsby dependencies)
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      # Create public folder for build output
      - name: Create public folder for build output
        run: mkdir -p public

      - name: Install packages
        run: npm install

      - name: Run Gatsby build
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: master
          folder: public
